name: AWRT

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: h29k.config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    strategy:
      matrix:
        device: [h29k]
    runs-on: ubuntu-22.04

    steps:
    - name: Optimize Disk Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Checkout Code
      uses: actions/checkout@main

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --reinstall -y build-essential gcc g++ g++-multilib libdeflate-dev libdeflate0 ninja-build

    - name: Clone Source Code
      run: |
        git clone --filter=blob:none --depth=2 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Check Git Repository
      run: |
        cd openwrt
        if ! git rev-parse --is-inside-work-tree; then
          echo "Not inside a Git repository, falling back to full build"
          echo "FULL_BUILD=true" >> $GITHUB_ENV
        else
          echo "FULL_BUILD=false" >> $GITHUB_ENV
        fi

    - name: Clean tmp and toolchain directories
      run: |
        rm -rf openwrt/tmp/*
        rm -rf openwrt/staging_dir/toolchain-*
        rm -rf openwrt/build_dir/target-*

    - name: Update & Install Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a || (echo "Retrying feeds update..." && sleep 5 && ./scripts/feeds update -a)
        ./scripts/feeds install -a || (echo "Retrying feeds install..." && sleep 5 && ./scripts/feeds install -a)

    - name: Load Configuration
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH
        make defconfig

    - name: Check if Toolchain Needs Rebuilding
      run: |
        if [ ! -d "openwrt/staging_dir/toolchain-*" ] || [ -z "$(ls -A openwrt/staging_dir/toolchain-*/lib/ld-musl-*.so* 2>/dev/null)" ]; then
          echo "TOOLCHAIN_REBUILD=true" >> $GITHUB_ENV
        else
          echo "TOOLCHAIN_REBUILD=false" >> $GITHUB_ENV
        fi

    - name: Rebuild Toolchain if Needed
      if: env.TOOLCHAIN_REBUILD == 'true'
      run: |
        cd openwrt
        echo "Toolchain is missing or incomplete, rebuilding..."
        make toolchain/install -j$(nproc) V=s

    - name: Determine Build Type (Full or Incremental)
      run: |
        cd openwrt
        if [[ "$FULL_BUILD" == "true" ]] || git diff --name-only HEAD^ | grep -qE "target|kernel"; then
            echo "Performing full compile"
            make -j$(nproc) > build.log 2>&1 || (echo "Build failed, showing last 100 lines of log:" && tail -n 100 build.log && exit 1)
        else
            echo "Performing incremental compile"
            make package/compile -j$(nproc) > build.log 2>&1 || (echo "Build failed, showing last 100 lines of log:" && tail -n 100 build.log && exit 1)
        fi

    - name: Upload Build Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-log
        path: openwrt/build.log

    - name: Show ccache stats
      run: |
        ccache -s
